# Generated by Django 3.1.7 on 2021-03-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_overcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='overcategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store.overcategory'),
            preserve_default=False,
        ),
    ]
